#!/bin/bash -e

GO_VERSION="1.16.4"
TERRAFORM_VERSION="1.0.5"

# Install Dependencies
apt-get update && apt-get upgrade -y
sudo apt-get install -y \
  apt-transport-https \
  autoconf \
  automake \
  bison \
  build-essential \
  ca-certificates \
  curl \
  git \
  gnupg gnupg-agent \
  gpg \
  keychain \
  libc6-dev libssl-dev libtool libxml2-dev libyaml-dev \
  openssl \
  python3 python3-pip \
  silversearcher-ag \
  software-properties-common \
  tmux \
  tree \
  unzip \
  vim \
  zlib1g zlib1g-dev \
  zsh

# Install Go
curl -L -o /tmp/go$GO_VERSION.tar.gz https://golang.org/dl/go$GO_VERSION.linux-amd64.tar.gz
tar -C /usr/local -xzf /tmp/go$GO_VERSION.tar.gz
rm /tmp/go$GO_VERSION.tar.gz
export PATH="$PATH:/usr/local/go/bin"

# Install Oh My Zsh
curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh

# Install git-chglog
go get -u github.com/git-chglog/git-chglog/cmd/git-chglog

# Install pre-commit
pip install pre-commit

# Install Terraform
wget -q -O - https://raw.githubusercontent.com/ethanhassett/tfvm/main/install.sh | bash
export PATH="$PATH:$HOME/.tfvm/bin"
tfvm install $TERRAFORM_VERSION
tfvm use $TERRAFORM_VERSION

# Install terraform-docs
GO111MODULE="on" go get github.com/terraform-docs/terraform-docs@v0.15.0

# Install Packer
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt-get install -y packer

# Install AWS CLI
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
unzip -q /tmp/awscliv2.zip -d /tmp
/tmp/aws/install
rm -rf /tmp/aws /tmp/awscliv2.zip

# Move files
mkdir -p ~/.oh-my-zsh/themes && mv /tmp/erhbg.zsh-theme ~/.oh-my-zsh/themes/erhbg.zsh-theme
mv /tmp/.zshrc ~/.zshrc
mkdir -p ~/.dir_colors && mv /tmp/dircolors.256darksolarized ~/.dir_colors/dircolors.256darksolarized

# Make Repo dir
mkdir $HOME/Repos